// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe3T6KayANISEV68zl7m3xNru0QDfEVEA',
    appId: '1:1040634878755:android:5719643122169e09920a96',
    messagingSenderId: '1040634878755',
    projectId: 'devera-flutter-do-an-cuoi-khoa',
    storageBucket: 'devera-flutter-do-an-cuoi-khoa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc4lndYiC_29iol0C9p3CoVxmAg-GZ51k',
    appId: '1:1040634878755:ios:3e2dc3523d0e1a8e920a96',
    messagingSenderId: '1040634878755',
    projectId: 'devera-flutter-do-an-cuoi-khoa',
    storageBucket: 'devera-flutter-do-an-cuoi-khoa.appspot.com',
    iosClientId: '1040634878755-f8vcqpabupi3ap45s7jjhjn7v23pc7kn.apps.googleusercontent.com',
    iosBundleId: 'com.example.deveraDoAnCuoiKhoa',
  );
}
